version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: uniboard_db
    environment:
      POSTGRES_USER: uniboard_user
      POSTGRES_PASSWORD: uniboard_password
      POSTGRES_DB: uniboard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: